### PR TITLE
Fix #6479 - remove IFileProvider constructor

### LINKED ISSUE #6479: [.netcore 2 preview 2] ifileprovider + di error
After upgrading to the latest preview release, I am now seeing the following error when starting up the application (via dotnet run):

System.InvalidOperationException: Unable to activate type 'Microsoft.AspNetCore.Mvc.Razor.Internal.FileProviderRazorProject'. The following constructors are ambigious:
Void .ctor(Microsoft.AspNetCore.Mvc.Razor.Internal.IRazorViewEngineFileProviderAccessor)
Void .ctor(Microsoft.Extensions.FileProviders.IFileProvider)

My application registers its own IFileProvider as part of startup, like this (also suggested here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers):

.AddSingleton<IFileProvider>(x => new PhysicalFileProvider(_config["Environment:AssetsPath"]))
 
If I comment out this line, then everything starts normally, but of course the functionality depending on this does not work.

Should this still work as before?

-- dotnet info:
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     fedora
 OS Version:  25
 OS Platform: Linux
 RID:         fedora.25-x64
 Base Path:   /opt/dotnet/sdk/2.0.0-preview2-006497/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

### PR DESCRIPTION
**Pull request by rynowak**
The RazorProject implementation used by MVC at runtime has a constructor
that takes an IFileProvider (used by tests). This causes ambiguities
when a user registers an IFileProvider in DI.

Cleaning up tests to use a mock instead of the file provider directly

### CODE REVIEW

File: samples/MvcSandbox/Startup.cs [hunk 1]
```diff
@@ -17,6 +20,7 @@ public class Startup
         public void ConfigureServices(IServiceCollection services)
         {
             services.AddMvc();
+            services.AddSingleton<IFileProvider>(new PhysicalFileProvider(Path.GetFullPath(".")));
```
Comment (pranavkm) [inline samples/MvcSandbox/Startup.cs]: Is this meant as verification? Need docs if it is.

File: test/Microsoft.AspNetCore.Mvc.Razor.Test/Internal/FileProviderRazorProjectTest.cs [hunk 2]
```diff
@@ -18,7 +19,9 @@ public void EnumerateFiles_ReturnsEmptySequenceIfNoCshtmlFilesArePresent()
             var file2 = fileProvider.AddFile("File2.js", "content");
             fileProvider.AddDirectoryContent("/", new IFileInfo[] { file1, file2 });
 
-            var razorProject = new FileProviderRazorProject(fileProvider);
+            var accessor = Mock.Of<IRazorViewEngineFileProviderAccessor>(a => a.FileProvider == fileProvider);
```
Comment (pranavkm) [inline test/Microsoft.AspNetCore.Mvc.Razor.Test/Internal/FileProviderRazorProjectTest.cs]: Their fluent setup is super weird

Comment (rynowak) [inline test/Microsoft.AspNetCore.Mvc.Razor.Test/Internal/FileProviderRazorProjectTest.cs]: I've actually become a huge fan of this, it scales way better than their builder API
